### PR TITLE
Semantic Release

### PR DESCRIPTION
**Pull request by aabenoja**
Automatically version, publish and generate changelogs on merge to master.

## `husky` + `commitlint`
`commitlint` is used to ensure the correct conventions are used in commit messages using huky's `commit-msg` hook. If the commit does not use the [`eslint conventions`](https://github.com/conventional-changelog/conventional-changelog/tree/35e279d40603b0969c6d622514f5c0984c5bf309/packages/conventional-changelog-eslint) the commit hook will fail. This can be bypassed with `--no-verify`. I am still not sure if we should keep this as an error or drop it down to at least a warning so we can make micro-commits without needing the bypass

### CODE REVIEW

**Comment by aabenoja** [comment]
I think this is ready to merge. Everything checks out with the dry run in [this release run](https://travis-ci.com/WTW-IM/babel-preset-wtw-im/jobs/153612388) - look in the "Deploying application" section for more details. There are only a couple of concerns:

1. Should we add a `CONTRIBUTING.md` or something to make it clear that we are using `semantic-release` using eslint conventions? I still don't know what such a guideline file would look like.
2. I still don't have publish rights to this repo or, at the very least, it's not showing up in my list of packages or as part of the developers team in the npm organization. I created an `NPM_TOKEN` in the travis-ci settings for this repo, but the token will not work if I don't have those permissions.

**Comment by aabenoja** [comment]
I have added a `Contributing` section to the `README`. Please have a look at it.

I have very mixed feelings about using a separate npm account.

On one hand, I think it's a good idea. I would prefer if npm provided a way to create organization-specific tokens. I do not like the idea of using our personal accounts to create publish tokens, as members can come and go for various reasons. Creating a separate account would put us a step in the right direction so that we don't have to worry about possible token juggling when someone leaves the org.

On the other hand, it is dead simple to go into your tokens page, generate and copy a new token, and replace the environment variable in each of our travis builds to use the newly generated token. With it being so simple creating a separate account for publishing seems like a waste. If another security breach occurs and everyone's tokens are cleared out we'd have to do this anyway.

**Comment by jrios** [comment]
Those are fair points. Not sure if they'll ever add organization-wide tokens. 

This looks good. Thanks @aabenoja for this work!

**Pull request merged**
